version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: finance
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: ./backend
    environment:
      ConnectionStrings__Default: Host=db;Database=finance;Username=user;Password=pass
    depends_on:
      - db
    ports:
      - "5000:80"
  web:
    build: ./frontend
    ports:
      - "3000:80"
volumes:
  pgdata:
